# Requires
# vagrant init fedora/23-cloud-base
# vagrant plugin install vagrant-vbguest
# vagrant plugin install vagrant-ansible-local

Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/vivid64"
  #config.vm.box = "centos/7"
  config.vm.box = "fedora/23-cloud-base"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "fedora_foo"
    vb.gui = true
    vb.memory = "2048"
    #vb.customize ["modifyvm", :id, "--accelerate3d", "on" ]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional" ]
  end
  
  config.vm.synced_folder "./ansible", "/ansible", type: "virtualbox"
  
  # https://github.com/mitchellh/vagrant/issues/3230#issuecomment-54714726
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  
  # Installs ansible to enable provision (Will always run)
  config.vm.provision :shell, :path => "ansible-bootstrap.sh"
  
  # Runs ansible locally
  config.vm.provision :ansibleLocal, :playbook => "ansible/playbook.yml", :raw_arguments => "-i 'localhost,'"
end